module.exports.wait = async (seconds) => {
    await new Promise((resolve) => setTimeout(() => resolve(), seconds*1000));
}

module.exports.keywords = [
    "Poluição",
    "Flora nativa",
    "Direito urbanístico ambiental",
    "Tratamento de resíduos sólidos",
    "Direito à consulta prévia",
    "Biodiversidade",
    "Ecossistemas",
    "Energia nuclear",
    "Direito à água",
    "Sustentabilidade empresarial",
    "Conservação",
    "Jurisprudência ambiental",
    "Obrigações ambientais",
    "Direito ao saneamento básico",
    "Crimes ambientais",
    "Emissões",
    "Tratados internacionais",
    "Tráfico de fauna e flora",
    "Política de energia",
    "Direito ao desenvolvimento",
    "Recursos naturais",
    "Direito ambiental comparado",
    "Biopirataria",
    "Direito à justiça ambiental",
    "Política de conservação marinha",
    "Impacto ambiental",
    "Educação ambiental",
    "Direito ambiental internacional",
    "Direito das cidades sustentáveis",
    "Direito à mobilidade sustentável",
    "Sustentabilidade",
    "Direito das águas",
    "Certificação ambiental",
    "Direito dos animais",
    "Direito à alimentação adequada",
    "Desenvolvimento sustentável",
    "Direito marítimo ambiental",
    "Regulamentação ambiental",
    "Responsabilidade penal ambiental",
    "Responsabilidade compartilhada",
    "Áreas protegidas",
    "Riscos ambientais",
    "Áreas de proteção permanente",
    "Direito à educação ambiental",
    "Direito ao meio ambiente ecologicamente equilibrado",
    "Direitos ambientais",
    "Política ambiental",
    "Direito ambiental empresarial",
    "Convenções ambientais",
    "Poluição do solo",
    "Legislação ambiental",
    "Responsabilidade civil ambiental",
    "Ecologia",
    "Direito das populações ribeirinhas",
    "Comércio de carbono",
    "Responsabilidade ambiental",
    "Avaliação de impacto ambiental",
    "Política de resíduos",
    "Bens ambientais",
    "Direito das áreas degradadas",
    "Licenciamento ambiental",
    "Zonas costeiras",
    "Ecossistemas aquáticos",
    "Direito à cultura ambiental",
    "Direito à igualdade ambiental",
    "Gestão de resíduos",
    "Direito ambiental indígena",
    "Direito dos povos tradicionais",
    "Direito à reparação ambiental",
    "Direito à tecnologia ambiental",
    "Florestas",
    "Poluição do ar",
    "Direito à saúde ambiental",
    "Bacias hidrográficas",
    "Política de resíduos perigosos",
    "Água potável",
    "Recursos hídricos",
    "Direito à participação pública",
    "Monitoramento ambiental",
    "Direito ao patrimônio cultural ambiental",
    "Energias renováveis",
    "Direito à informação ambiental",
    "Poluição sonora",
    "Direito à segurança ambiental",
    "Direito das unidades de conservação",
    "Mudanças climáticas",
    "Reservas naturais",
    "Direito das gerações futuras",
    "Áreas de recuperação ambiental",
    "Resíduos radioativos",
    "Proteção do solo",
    "Espécies ameaçadas",
    "Áreas de preservação permanente",
    "Direito ao acesso à informação",
    "Direito ao patrimônio genético",
    "Fauna silvestre",
    "Agricultura sustentável",
    "Desmatamento",
    "Efeito estufa",
    "Direito à bioética"
]